/**
 * Renders a reasoning graph as one self-contained HTML file: no CDN, no
 * framework, no build step, no external requests -- same bar as web/index.html,
 * but a top-down collapsible tree rather than force-directed physics, since a
 * decision tree reads better top-down. Pure string templating, no fs access.
 */
function escapeHtml(s) {
  return String(s).replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));
}

function renderLabel(n) {
  const riskDot = n.risk ? `<span class="dot risk-${n.risk}"></span>` : "";
  return `<span class="node-row" data-id="${escapeHtml(n.id)}"><span class="pill status-${n.status}">${n.status}</span>${riskDot}<span class="title">${escapeHtml(n.title)}</span></span>`;
}

function renderNode(graph, id) {
  const n = graph.nodes[id];
  const label = renderLabel(n);
  if (!n.children.length) return `<div class="node leaf">${label}</div>`;
  const childrenHtml = n.children.map((c) => renderNode(graph, c)).join("");
  return `<details open class="node"><summary>${label}</summary><div class="children">${childrenHtml}</div></details>`;
}

function decisionNodes(graph) {
  return Object.values(graph.nodes).filter((n) => n.type !== "feature");
}

// Embedding raw JSON inside <script type="application/json"> is safe from
// execution, but a title containing a literal "</script>" would still close
// the tag early to the HTML parser -- escaping "<" as < (valid inside a
// JSON string) keeps JSON.parse working while making that impossible.
function embeddableJson(graph) {
  return JSON.stringify(graph).replace(/</g, "\\u003c");
}

export function renderHtml(graph) {
  const resolved = decisionNodes(graph).filter((n) => n.status === "resolved").length;
  const total = decisionNodes(graph).length;
  const tree = renderNode(graph, graph.root_id);

  return `<!doctype html>
<!--
  Reasoning graph for "${escapeHtml(graph.feature)}".

  Self-contained: no CDN, no framework, no build step, no external requests --
  same bar as web/index.html. Regenerated by create_reasoning_graph and
  update_reasoning_graph; hand-edit graph.json, not this file, since the next
  patch overwrites it.
-->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Reasoning — ${escapeHtml(graph.feature)}</title>
<style>
  :root {
    color-scheme: light dark;
    --bg: #fbfbfd; --fg: #17181c; --muted: #6b6f76; --line: #dfe1e6;
    --panel: #fff; --accent: #2f6fed; --risk: #d1453b; --warm: #e0873a;
  }
  @media (prefers-color-scheme: dark) {
    :root {
      --bg: #16171b; --fg: #e9eaee; --muted: #9297a1; --line: #2c2e35;
      --panel: #1e2025; --accent: #6c9bff; --risk: #f0685c; --warm: #edab6a;
    }
  }
  * { box-sizing: border-box; }
  body {
    margin: 0; background: var(--bg); color: var(--fg);
    font: 14px/1.5 ui-sans-serif, -apple-system, "Segoe UI", system-ui, sans-serif;
  }
  header {
    display: flex; gap: 12px; align-items: baseline; flex-wrap: wrap;
    padding: 12px 16px; border-bottom: 1px solid var(--line); background: var(--panel);
  }
  h1 { font-size: 15px; margin: 0; font-weight: 650; letter-spacing: -0.01em; }
  .summary { color: var(--muted); font-size: 12px; }
  main { display: grid; grid-template-columns: minmax(0, 1fr) 340px; height: calc(100vh - 54px); }
  @media (max-width: 820px) { main { grid-template-columns: 1fr; grid-template-rows: 55vh auto; } }
  #tree { overflow-y: auto; padding: 14px 16px; }
  aside { border-left: 1px solid var(--line); background: var(--panel); padding: 14px 16px; overflow-y: auto; }
  @media (max-width: 820px) { aside { border-left: 0; border-top: 1px solid var(--line); } }
  details.node { margin: 2px 0 2px 16px; }
  details.node > summary { list-style: none; cursor: pointer; }
  details.node > summary::-webkit-details-marker { display: none; }
  .node.leaf { margin: 2px 0 2px 16px; }
  .node-row { display: inline-flex; align-items: center; gap: 6px; padding: 3px 6px; border-radius: 6px; }
  .node-row:hover, .node-row.sel { background: var(--line); }
  .pill { font-size: 10px; padding: 1px 6px; border-radius: 999px; border: 1px solid var(--line); color: var(--muted); }
  .pill.status-resolved { color: var(--accent); border-color: var(--accent); }
  .dot { width: 8px; height: 8px; border-radius: 50%; display: inline-block; }
  .dot.risk-low { background: #2fa84f; }
  .dot.risk-medium { background: var(--warm); }
  .dot.risk-high { background: var(--risk); }
  aside h2 { font-size: 14px; margin: 0 0 8px; }
  aside h3 { font-size: 11px; text-transform: uppercase; letter-spacing: .04em; color: var(--muted); margin: 16px 0 6px; }
  .alt { border: 1px solid var(--line); border-radius: 8px; padding: 8px 10px; margin-bottom: 8px; }
  .alt.selected { border-color: var(--accent); }
  .alt ul { margin: 4px 0; padding-left: 18px; }
  .files li, .empty { color: var(--muted); }
</style>
</head>
<body>
<header>
  <h1>${escapeHtml(graph.feature)}</h1>
  <span class="summary">${resolved} of ${total} resolved · updated ${escapeHtml(graph.updated_at)}</span>
</header>
<main>
  <div id="tree">${tree}</div>
  <aside id="inspector"></aside>
</main>
<script type="application/json" id="graph-data">${embeddableJson(graph)}</script>
<script>
(function () {
  var graph = JSON.parse(document.getElementById('graph-data').textContent);
  var inspector = document.getElementById('inspector');

  function esc(s) {
    return String(s).replace(/[&<>"]/g, function (c) {
      return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c];
    });
  }

  function renderInspector(node) {
    var html = '<h2>' + esc(node.title) + '</h2>';
    html += '<div class="pill status-' + node.status + '">' + node.status + '</div>';
    if (node.risk) html += ' <span class="dot risk-' + node.risk + '"></span> ' + node.risk;
    if (node.alternatives && node.alternatives.length) {
      html += '<h3>Alternatives</h3>';
      node.alternatives.forEach(function (alt) {
        html += '<div class="alt' + (alt.id === node.selected ? ' selected' : '') + '">';
        html += '<strong>' + esc(alt.label) + '</strong>';
        if (alt.pros && alt.pros.length) html += '<ul>' + alt.pros.map(function (p) { return '<li>+ ' + esc(p) + '</li>'; }).join('') + '</ul>';
        if (alt.cons && alt.cons.length) html += '<ul>' + alt.cons.map(function (c) { return '<li>- ' + esc(c) + '</li>'; }).join('') + '</ul>';
        html += '</div>';
      });
    }
    html += '<h3>Affected files</h3>';
    html += (node.affected_files && node.affected_files.length)
      ? '<ul class="files">' + node.affected_files.map(function (f) { return '<li>' + esc(f) + '</li>'; }).join('') + '</ul>'
      : '<div class="empty">None recorded</div>';
    if (node.notes) html += '<h3>Notes</h3><div>' + esc(node.notes) + '</div>';
    inspector.innerHTML = html;
  }

  document.querySelectorAll('.node-row').forEach(function (row) {
    row.addEventListener('click', function () {
      document.querySelectorAll('.node-row.sel').forEach(function (r) { r.classList.remove('sel'); });
      row.classList.add('sel');
      renderInspector(graph.nodes[row.getAttribute('data-id')]);
    });
  });

  renderInspector(graph.nodes[graph.root_id]);
})();
</script>
</body>
</html>
`;
}
